/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1_201504100;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author cr-al
 */
public class Tablero extends javax.swing.JFrame {

    Reportes reporte = new Reportes();

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_fichas = new javax.swing.JPanel();
        ficha1 = new javax.swing.JButton();
        ficha3 = new javax.swing.JButton();
        ficha6 = new javax.swing.JButton();
        ficha2 = new javax.swing.JButton();
        ficha4 = new javax.swing.JButton();
        ficha5 = new javax.swing.JButton();
        ficha7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        texto_usuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        texto_nueva_palabra = new javax.swing.JTextField();
        Agregar_Diccionario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        checkbox_ficha1 = new javax.swing.JCheckBox();
        label_ficha1 = new javax.swing.JLabel();
        checkbox_ficha2 = new javax.swing.JCheckBox();
        label_ficha2 = new javax.swing.JLabel();
        checkbox_ficha3 = new javax.swing.JCheckBox();
        label_ficha3 = new javax.swing.JLabel();
        checkbox_ficha4 = new javax.swing.JCheckBox();
        label_ficha4 = new javax.swing.JLabel();
        checkbox_ficha5 = new javax.swing.JCheckBox();
        label_ficha5 = new javax.swing.JLabel();
        checkbox_ficha_ficha6 = new javax.swing.JCheckBox();
        label_ficha6 = new javax.swing.JLabel();
        checkbox_ficha7 = new javax.swing.JCheckBox();
        label_ficha7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        principal = new javax.swing.JTabbedPane();
        label_diccionario = new javax.swing.JLabel();
        label_fichas_activas = new javax.swing.JLabel();
        label_cola = new javax.swing.JLabel();
        label_jugadores = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        panel_fichas.setBackground(new java.awt.Color(51, 255, 51));

        ficha1.setText("jButton1");

        ficha3.setText("jButton1");

        ficha6.setText("jButton1");

        ficha2.setText("jButton1");

        ficha4.setText("jButton1");

        ficha5.setText("jButton1");

        ficha7.setText("jButton1");

        javax.swing.GroupLayout panel_fichasLayout = new javax.swing.GroupLayout(panel_fichas);
        panel_fichas.setLayout(panel_fichasLayout);
        panel_fichasLayout.setHorizontalGroup(
            panel_fichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fichasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ficha1)
                .addGap(18, 18, 18)
                .addComponent(ficha2)
                .addGap(11, 11, 11)
                .addComponent(ficha3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ficha4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ficha5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ficha6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ficha7)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        panel_fichasLayout.setVerticalGroup(
            panel_fichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fichasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_fichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ficha1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Turno de :");

        texto_usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texto_usuario.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Area de Reportes");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Puntuacion");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nueva Palabra");

        Agregar_Diccionario.setText("Agregar");
        Agregar_Diccionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_DiccionarioActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Cambiar Letra");

        checkbox_ficha1.setText("jCheckBox1");

        label_ficha1.setText("jLabel6");

        checkbox_ficha2.setText("jCheckBox2");

        label_ficha2.setText("jLabel7");

        checkbox_ficha3.setText("jCheckBox3");

        label_ficha3.setText("jLabel8");

        checkbox_ficha4.setText("jCheckBox4");

        label_ficha4.setText("jLabel9");

        checkbox_ficha5.setText("jCheckBox5");

        label_ficha5.setText("jLabel10");

        checkbox_ficha_ficha6.setText("jCheckBox6");
        checkbox_ficha_ficha6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_ficha_ficha6ActionPerformed(evt);
            }
        });

        label_ficha6.setText("jLabel11");

        checkbox_ficha7.setText("jCheckBox7");

        label_ficha7.setText("jLabel12");

        jButton1.setText("Cambiar Letra");

        label_diccionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1_201504100/grafoDiccionario.jpg"))); // NOI18N
        label_diccionario.setText("jLabel6");
        principal.addTab("Lista_Diccionario", label_diccionario);

        label_fichas_activas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1_201504100/grafoFichas_Usuario.jpg"))); // NOI18N
        label_fichas_activas.setText("jLabel6");
        principal.addTab("Lista de Fichas Activas", label_fichas_activas);

        label_cola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1_201504100/grafoCola_FichasPendientes.jpg"))); // NOI18N
        label_cola.setText("jLabel6");
        principal.addTab("Cola de Fichas", label_cola);

        label_jugadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1_201504100/grafoUsuarios.jpg"))); // NOI18N
        label_jugadores.setText("jLabel6");
        principal.addTab("Lista de Jugadores", label_jugadores);

        jButton2.setText("Reportes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_fichas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(texto_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(texto_nueva_palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Agregar_Diccionario)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(checkbox_ficha4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(checkbox_ficha3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(checkbox_ficha2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(checkbox_ficha1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_ficha4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(label_ficha2)
                                                .addGap(18, 18, 18)
                                                .addComponent(checkbox_ficha_ficha6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(label_ficha1)
                                                .addGap(18, 18, 18)
                                                .addComponent(checkbox_ficha5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(label_ficha5)
                                            .addComponent(label_ficha6)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label_ficha3)
                                        .addGap(18, 18, 18)
                                        .addComponent(checkbox_ficha7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(label_ficha7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton1))))
                            .addComponent(jLabel5))))
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(10, 10, 10)
                                        .addComponent(texto_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jButton2)))
                                .addGap(83, 83, 83)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(texto_nueva_palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Agregar_Diccionario)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_fichas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkbox_ficha1)
                            .addComponent(label_ficha1)
                            .addComponent(checkbox_ficha5)
                            .addComponent(label_ficha5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkbox_ficha2)
                            .addComponent(label_ficha2)
                            .addComponent(checkbox_ficha_ficha6)
                            .addComponent(label_ficha6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkbox_ficha3)
                            .addComponent(label_ficha3)
                            .addComponent(checkbox_ficha7)
                            .addComponent(label_ficha7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkbox_ficha4)
                            .addComponent(label_ficha4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Agregar_DiccionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_DiccionarioActionPerformed
        // TODO add your handling code here:
        agregarDiccionario();
    }//GEN-LAST:event_Agregar_DiccionarioActionPerformed

    private void checkbox_ficha_ficha6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_ficha_ficha6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkbox_ficha_ficha6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            reporte.Reporte_Usuarios();
            //URL url = this.getClass().getResource("C://Graph//grafoUsuarios.jpg");
            String  url = "C://Graph//grafoUsuarios.jpg";
            ImageIcon icon1 = new ImageIcon(url);
            Icon icono1=new ImageIcon(icon1.getImage().getScaledInstance(label_jugadores.getWidth(), label_jugadores.getHeight(), Image.SCALE_DEFAULT));
            this.label_jugadores.setIcon(icono1);

            reporte.Reporte_Fichas_Pendientes();
            String url2 = "C://Graph//grafoCola_FichasPendientes.jpg";
            ImageIcon icon2 = new ImageIcon(url2);
            Icon icono2=new ImageIcon(icon2.getImage().getScaledInstance(label_cola.getWidth(), label_cola.getHeight(), Image.SCALE_DEFAULT));
            this.label_cola.setIcon(icono2);

            reporte.Reporte_Fichas_Usuarios("user1");
            
            String url3 = "C://Graph//grafoFichas_Usuario.jpg";
            ImageIcon icon3 = new ImageIcon(url3);
            Icon icono3=new ImageIcon(icon3.getImage().getScaledInstance(label_fichas_activas.getWidth(), label_fichas_activas.getHeight(), Image.SCALE_DEFAULT));
            this.label_fichas_activas.setIcon(icono3);
            
            reporte.Reporte_Diccionario();
            
            String url4 = "C://Graph//grafoDiccionario.jpg";
            ImageIcon icon4 = new ImageIcon(url4);
            Icon icono4=new ImageIcon(icon4.getImage().getScaledInstance(label_diccionario.getWidth(), label_diccionario.getHeight(), Image.SCALE_DEFAULT));
            this.label_diccionario.setIcon(icono4);
        } catch (IOException ex) {
            Logger.getLogger(VentanaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public void agregarDiccionario() {
        if (texto_nueva_palabra.getText() != "") {
            if (LeerXML.lista_simple.buscar(texto_nueva_palabra.getText())) {
                JOptionPane.showMessageDialog(null, "Palabra ya existente en el diccionario");
            } else {
                LeerXML.lista_simple.agregarAlFinal(texto_nueva_palabra.getText());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //En este metodo se colocan los metodos antes de cargar el tablero
                new Tablero().setVisible(true);

            }

        });
    }

    public void reportes() {

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_Diccionario;
    private javax.swing.JCheckBox checkbox_ficha1;
    private javax.swing.JCheckBox checkbox_ficha2;
    private javax.swing.JCheckBox checkbox_ficha3;
    private javax.swing.JCheckBox checkbox_ficha4;
    private javax.swing.JCheckBox checkbox_ficha5;
    private javax.swing.JCheckBox checkbox_ficha7;
    private javax.swing.JCheckBox checkbox_ficha_ficha6;
    private javax.swing.JButton ficha1;
    private javax.swing.JButton ficha2;
    private javax.swing.JButton ficha3;
    private javax.swing.JButton ficha4;
    private javax.swing.JButton ficha5;
    private javax.swing.JButton ficha6;
    private javax.swing.JButton ficha7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_cola;
    private javax.swing.JLabel label_diccionario;
    private javax.swing.JLabel label_ficha1;
    private javax.swing.JLabel label_ficha2;
    private javax.swing.JLabel label_ficha3;
    private javax.swing.JLabel label_ficha4;
    private javax.swing.JLabel label_ficha5;
    private javax.swing.JLabel label_ficha6;
    private javax.swing.JLabel label_ficha7;
    private javax.swing.JLabel label_fichas_activas;
    private javax.swing.JLabel label_jugadores;
    private javax.swing.JPanel panel_fichas;
    private javax.swing.JTabbedPane principal;
    private javax.swing.JTextField texto_nueva_palabra;
    private javax.swing.JLabel texto_usuario;
    // End of variables declaration//GEN-END:variables
}
